{
    'name': "School Management",
    'version': '1.0',
    'type': 'module',
    'depends': ['base','mail','sale','website', 'website_sale',],
    'author': "San",
    'category': 'Category',
    'description': """ Manage the students and activities of a school """,
    # data files always loaded at installation
    'data': [
        'security/school_user_groups.xml',
        'security/school_security.xml',
        'security/ir.model.access.csv',
        'data/school_department_data.xml',
        'data/school_class_data.xml',
        'data/school_subject_data.xml',
        'data/ir_sequence_data.xml',
        'data/mail_tempalate_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_action_data.xml',
        'data/portal_menu.xml',
        'views/snippets/school_category_template.xml',
        'views/sale_order_view.xml',
        'views/registration_view.xml',
        'views/department_view.xml',
        'views/class_view.xml',
        'views/subject_view.xml',
        'views/academic_year_view.xml',
        'views/club_view.xml',
        'views/event_view.xml',
        'views/school_teacher_view.xml',
        'views/school_leave_views.xml',
        'views/school_exam_view.xml',
        'views/school_web_form_template.xml',
        'views/school_web_list_template.xml',
        # 'views/website_sale_custom_views.xml',
        'report/ir_actions_report.xml',
        'report/leave_report_template.xml',
        'report/student_report_template.xml',
        'wizard/student_inform.xml',
        'wizard/student_leave.xml',
        'views/school_management_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'school/static/src/js/action_manager.js',
            # 'school/static/src/js/school_events.js',
        ],
        'web.assets_frontend': [
            'school/static/src/js/school_events.js',
            'school/static/src/xml/event_highlight_website.xml',
        ],

    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 1,

}
